package jframe;

import base.BaseDeDatos;
import base.GestorDePedidos;
import fabrica.comprobante.BoletaFabrica;
import fabrica.comprobante.ComprobanteFabrica;
import java.awt.BorderLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Comprobante;
import modelo.Pedido;
import modelo.Producto;
import servicio.CarritoServicio;
import servicio.PedidoServicio;
import servicio.ProcesadorPedido;
import test.CargadorDeCliente;
import test.CargadorDeProductos;

public class Tienda extends javax.swing.JFrame {
    private BaseDeDatos db;
    private Cliente cliente;
    private GestorDePedidos gestorPedidos;
    private CarritoServicio carrito;
    private BoletaFabrica fabricacomprobante;
    
    /**
     * Creates new form Tienda
     */
    public Tienda() {
        initComponents();
        db = BaseDeDatos.getInstancia();
        gestorPedidos = GestorDePedidos.getInstancia();
        CargadorDeProductos.cargarProductos(db);
        cliente = CargadorDeCliente.cargarCliente();
        carrito = new CarritoServicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        comboCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        botonEjecutar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboCategoria.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una categoria", "Consolas", "Videojuegos", "Accesorios" }));
        comboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 87, 179, -1));

        tablaProductos.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Plataforma", "Categoria", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 395, 300));

        tablaCarrito.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Categoria", "Plataforma", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaCarrito);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 150, 277, 115));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setText("Carrito");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 111, -1, -1));

        botonAgregar.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        botonAgregar.setText("Agregar al Carrito");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 462, -1, -1));

        botonEjecutar.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        botonEjecutar.setText("Realizar Pedido");
        botonEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEjecutarActionPerformed(evt);
            }
        });
        jPanel2.add(botonEjecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 381, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setText("TIENDA VIRTUAL DE SONY");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 32, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEjecutarActionPerformed
        PedidoServicio serviciopedido = new PedidoServicio(carrito);
        Pedido pedido = serviciopedido.crearPedido(cliente);
        ProcesadorPedido proceso = new ProcesadorPedido(pedido);
        proceso.start();
        try {
            proceso.join();
        } catch (InterruptedException ex) {
            Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
        }

        fabricacomprobante = new BoletaFabrica();

        Comprobante boleta = fabricacomprobante.crearComprobante(pedido);
        boleta.mostrar();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripción");
        modelo.addColumn("Categoría");
        modelo.addColumn("Precio");
        modelo.setRowCount(0);
        tablaCarrito.setModel(modelo);
        carrito.vaciarCarrito();
    }//GEN-LAST:event_botonEjecutarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        int filaSeleccionada = tablaProductos.getSelectedRow();

        if (filaSeleccionada != -1) {
            DefaultTableModel modeloProductos = (DefaultTableModel) tablaProductos.getModel();
            DefaultTableModel modeloCarrito = (DefaultTableModel) tablaCarrito.getModel();

            int columnas = modeloProductos.getColumnCount();
            Object[] fila = new Object[columnas];

            for (int i = 0; i < columnas; i++) {
                fila[i] = modeloProductos.getValueAt(filaSeleccionada, i);
            }
            Producto producto = db.getProducto(fila[0].toString());
            carrito.agregarAlCarrito(producto);

            modeloCarrito.addRow(fila);
            JOptionPane.showMessageDialog(this, "Producto agregado al carrito con exito!");
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un producto.");
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void comboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoriaActionPerformed
        String opcion = (String) comboCategoria.getSelectedItem();
        List<Producto> productosCategoria = new ArrayList<>();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripción");
        modelo.addColumn("Categoría");
        modelo.addColumn("Precio");

        switch(opcion) {
            case "Consolas":
            productosCategoria = db.getConsolas();
            break;
            case "Videojuegos":
            productosCategoria = db.getVideojuegos();
            break;
            case "Accesorios":
            productosCategoria = db.getAccesorios();
            break;
            default:
            modelo.setRowCount(0);
            break;
        }

        for (Producto p : productosCategoria) {
            modelo.addRow(new Object[] {
                p.getNombre(),
                p.getDescripcion(),
                p.getCategoria(),
                p.getPrecio()
            });
        }

        tablaProductos.setModel(modelo);

    }//GEN-LAST:event_comboCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonEjecutar;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
