/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uni.edu.pc1;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Random;

/**
 *
 * @author HP
 */
public class MenuComprobante extends javax.swing.JFrame {

    /**
     * Creates new form MenuBoleta
     */
    public MenuComprobante() {
        initComponents();
    }
    //Funciones creadas
    public String generarCodigo() { //Función que genera el código de comprobante
        Random rand = new Random();
        String numero = "";
        int i;
        
        for(i = 0; i < 5; i++) {
            numero += String.valueOf(rand.nextInt(10));
        }
        
        return numero;
    };
    public static boolean isNumeric( String s ){ //Función que verifica si un string es numerico o no
        try{
            double y = Double.parseDouble( s );
            return true;
        }   catch( NumberFormatException err ){
            return false;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boxtipo = new javax.swing.JComboBox<>();
        txtcod = new javax.swing.JTextField();
        boxdoc = new javax.swing.JComboBox<>();
        txtdoc = new javax.swing.JTextField();
        txtdia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtmes = new javax.swing.JTextField();
        txtanio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtcodigoprod = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtunit = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        btngenerate = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        numdesc = new javax.swing.JSpinner();
        radiodesc = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel1.setText("Fecha");

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel3.setText("Documento");

        jLabel4.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel4.setText("Tipo CP");

        boxtipo.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        boxtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boleta", "Factura" }));
        boxtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxtipoActionPerformed(evt);
            }
        });

        txtcod.setEditable(false);
        txtcod.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodActionPerformed(evt);
            }
        });

        boxdoc.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        boxdoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "RUC" }));

        txtdoc.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N

        txtdia.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel8.setText("-");

        txtmes.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        txtmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmesActionPerformed(evt);
            }
        });

        txtanio.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel9.setText("-");

        txtname.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N

        table.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Precio Unit.", "Precio IGV", "Cantidad", "Descuento", "Importe T."
            }
        ));
        jScrollPane1.setViewportView(table);

        btngenerate.setBackground(new java.awt.Color(153, 204, 255));
        btngenerate.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        btngenerate.setText("Añadir a la lista");
        btngenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerateActionPerformed(evt);
            }
        });

        btn.setBackground(new java.awt.Color(153, 204, 255));
        btn.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        btn.setText("Generar Comprobante");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        numdesc.setEnabled(false);

        radiodesc.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        radiodesc.setText("Descuento");
        radiodesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiodescActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel5.setText("Detalles del Producto");

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel6.setText("Detalles del Cliente");

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel7.setText("Código Prod.");

        jLabel10.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel10.setText("Nombre Prod.");

        jLabel11.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel11.setText("Precio Unit.");

        jLabel12.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel12.setText("Cantidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boxdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(28, 28, 28)
                                        .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel8)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addGap(3, 3, 3)
                                        .addComponent(txtanio, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boxtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel6)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtcodigoprod, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtunit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(radiodesc))))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(btngenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(boxdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(boxtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtcodigoprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtunit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radiodesc))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btngenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerateActionPerformed
        //Variables que guardan la información que están en los txtfield
        String codigo = txtcodigoprod.getText();
        String nombre = txtnombre.getText();
        String punit = txtunit.getText();
        String cantidad = txtcantidad.getText();
        
        //Variables numéricas para el uso de operaciones
        Double nunit;
        Double nprecio;
        int ncantidad;
        Double nimporte;

        //Comprobaciones
        if(!isNumeric(codigo) || codigo.length() < 0) {
            System.out.println("Tienes que ingresar un codigo valido (tipo numerico)");
            return;
        }
        if(!isNumeric(punit) || Double.parseDouble(punit) < 0) {
            System.out.println("Tienes que ingrear un precio unitario valido");
            return;
        }
        if(!isNumeric(cantidad) || Integer.parseInt(cantidad) < 0) {
            System.out.println("Tienes que ingrear una cantidad valida");
            return;
        }
        
        //Definición de las variables
        nunit = Double.parseDouble(punit);
        ncantidad = Integer.parseInt(cantidad);
        nprecio = (double) Math.round(nunit * 118) / 100;
        String descuento = "No aplica";
        Double ndescuento;
        
        //Comprobación para productos con descuento
        if(numdesc.isEnabled()) {
            descuento = numdesc.getValue().toString();
            ndescuento = Double.parseDouble(descuento);
            if(ndescuento < 0 || ndescuento > 100) {
                return;
            }
            descuento += "%";
            ndescuento *= nprecio * ncantidad;
            ndescuento = (double) Math.round(ndescuento) / 100;
            nimporte = nprecio * ncantidad - ndescuento;
        }   else{
            nimporte = nprecio * ncantidad;
        }
        
        //convertir en string los valores hallados, para guardarlos en el array
        String precio = String.valueOf(nprecio);
        String importe = String.valueOf(nimporte);
        String[] arraycodigo = {codigo, nombre, punit, precio, cantidad, descuento, importe};
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.addRow(arraycodigo);
    }//GEN-LAST:event_btngenerateActionPerformed

    private void txtmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmesActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        //Comprobación que los datos de la fecha sean números y cumplan con la sintáxis de la fecha
        String dia = txtdia.getText();
        String mes = txtmes.getText();
        String anio = txtanio.getText();
        String fecha = "";
        if(!anio.isEmpty() && !mes.isEmpty() && !dia.isEmpty()) {
            if(!isNumeric(anio) || anio.length() != 4) {
                System.out.println("Tienes que ingresar un anio valido (4 digitos)");
                return;
            }
            if(!isNumeric(mes) || Integer.parseInt(mes) > 12 || Integer.parseInt(mes) <= 0) {
                System.out.println("Tienes que ingresar un mes valido (1 - 12)");
                return;
            }
            if(!isNumeric(dia) || Integer.parseInt(dia) > 30 || Integer.parseInt(dia) <= 0) {
                System.out.println("Tienes que ingresar un dia valido (1 - 30)");
                return;
            }
            fecha = dia + "/" + mes + "/" + anio;
        }
        
        
        //Declaración y definición de variables
        String nombre = txtname.getText();
        String seldoc = String.valueOf(boxdoc.getSelectedItem());
        String doc = txtdoc.getText();
        String tipo = String.valueOf(boxtipo.getSelectedItem());
        String codigo = txtcod.getText();
        
        //excepciones
        if(nombre.isEmpty()) {
            return;
        }
        switch(seldoc) {
            case "DNI" -> {
                if(!isNumeric(doc) || doc.length() != 8  || tipo.equals("Factura")) {
                    System.out.println("No se han ingresado los datos correctos, DNI tiene que ir con Boleta y tiene que tener 8 digitos");
                    return;
                }
            }
            case "RUC" -> {
                if(!isNumeric(doc) || doc.length() != 11 || tipo.equals("Boleta")) {
                    System.out.println("No se han ingresado los datos correctos, RUC tiene que ir con Factura y tiene que tener 11 digitos");
                    return;
                }
            }
        }
        
        //Declaración y definición de objetos
        Cliente cliente = new Cliente(nombre, seldoc, doc);
        Comprobante comprobante;
        if(fecha.equals("")) {
            if(tipo.equals("Boleta")) {
                comprobante = new Boleta(cliente, codigo);
            }   else {
                comprobante = new Factura(cliente, codigo);
            }
        }   else {
            if(tipo.equals("Boleta")) {
                comprobante = new Boleta(cliente, fecha, codigo);
            }   else{
                comprobante = new Factura(cliente, fecha, codigo);
            }
            
        }
        for(int fila = 0; fila < table.getRowCount(); fila++) {
            //Obtengo el valor de cada elemento de la tabla, para agregar a mi producto
            String codigoprod = table.getValueAt(fila, 0).toString();
            String nombreprod = table.getValueAt(fila, 1).toString();
            double preciounitprod = Double.parseDouble(table.getValueAt(fila, 2).toString());
            int cantidadprod = Integer.parseInt(table.getValueAt(fila, 4).toString());
            String descuentoprod = table.getValueAt(fila, 5).toString();
            descuentoprod = descuentoprod.replace("%", "");
            
            Producto producto;
            if (descuentoprod.equals("No aplica")) {
                producto = new ProductoNormal(nombreprod, preciounitprod, cantidadprod, codigoprod);
            } else {
                producto = new ProductoConDescuento(nombreprod, preciounitprod, cantidadprod, codigoprod, Double.parseDouble(descuentoprod));
            }
            comprobante.AgregarProducto(producto);
        }
        
        //Visualización del comprobante de pago
        System.out.println(comprobante.GenerarComprobante());
        
        
    }//GEN-LAST:event_btnActionPerformed

    private void radiodescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiodescActionPerformed
        //habilitar el descuento si el radio button se activa
        if(numdesc.isEnabled()) {
            numdesc.setEnabled(false);
        }   else{ 
            numdesc.setEnabled(true);
        }
    }//GEN-LAST:event_radiodescActionPerformed

    private void boxtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxtipoActionPerformed
        //Guardar las variables del txtfield y el combo box
        String tipo = boxtipo.getSelectedItem().toString();
        String codigo = txtcod.getText();
        
        //Comprobar si lo que contiene el txtfield no está vacío
        if(codigo.length() != 0) {
            if(tipo.charAt(0) == codigo.charAt(0)) {
                return;
            }
        }
        
        //Añadir un caracter al inicio de mi string codigo
        switch(tipo) {
            case "Factura" -> codigo = "F";
            case "Boleta" -> codigo = "B";
        }
        
        //guardar y presentar
        codigo += generarCodigo();
        txtcod.setText(codigo);
    }//GEN-LAST:event_boxtipoActionPerformed

    private void txtcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxdoc;
    private javax.swing.JComboBox<String> boxtipo;
    private javax.swing.JButton btn;
    private javax.swing.JButton btngenerate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner numdesc;
    private javax.swing.JRadioButton radiodesc;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtanio;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtcodigoprod;
    private javax.swing.JTextField txtdia;
    private javax.swing.JTextField txtdoc;
    private javax.swing.JTextField txtmes;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtunit;
    // End of variables declaration//GEN-END:variables

}
