package ui;

import ui.GestionPersonasFrame;
import java.sql.Connection;
import conexion.Conexion;

public class MenuUI extends javax.swing.JFrame {

    private GestionPersonasFrame p;
    private Connection conexion;
    private final int WIDTH = 1300;
    private final int HEIGHT = 600;
    public MenuUI() {
        initComponents();
        this.setSize(WIDTH, HEIGHT);
        desktop.setSize(WIDTH, HEIGHT);
        this.setLocationRelativeTo(null);
        this.setTitle("GESTOR DE PERSONAS");
        this.setResizable(false);
        conexion = Conexion.obtenerConexion();
        String textoconexion;
        if(conexion != null) {
            textoconexion = "Conexion exitosa!";
            
        }   else {
            textoconexion = "Error al conectar la base de datos";
        }
        txtConexion.setText(textoconexion);
        p = new GestionPersonasFrame(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        botonPersona = new javax.swing.JButton();
        txtConexion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPersona.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        botonPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-interface.png"))); // NOI18N
        botonPersona.setText("Persona");
        botonPersona.setContentAreaFilled(false);
        botonPersona.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonPersona.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonaActionPerformed(evt);
            }
        });

        txtConexion.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtConexion.setText("sd");

        desktop.setLayer(botonPersona, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(txtConexion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(botonPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGap(566, 566, 566)
                        .addComponent(txtConexion)))
                .addContainerGap())
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtConexion)
                .addGap(57, 57, 57)
                .addComponent(botonPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonaActionPerformed
        if(!p.isVisible()) {
             desktop.add(p);
            p.setVisible(true);
        }
    }//GEN-LAST:event_botonPersonaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPersona;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel txtConexion;
    // End of variables declaration//GEN-END:variables
}
